<table class="table">
    <tr>
        <th>Module</th>
        <th>Version</th>
        <th>HEAD</th>
        <th>upstream/master</th>
        <th>Status</th>
    </tr>
    <?php foreach ($this->modules as $name => $data) : ?>
    <tr>
        <td><?php echo $name; ?></td>
        <td><?php echo $data['version']; ?></td>
        <td><?php echo $data['localHash']; ?></td>
        <td><?php echo $data['remoteHash']; ?></td>
        <td><span class="label label-<?php if ($data['status'] == \AtAdminModules\Service\Module::STATUS_UP_TO_DATE): ?>success<?php else: ?>default<?php endif; ?>"><?php echo $data['status']; ?></span></td>
    </tr>
    <?php endforeach; ?>
</table>